### PR TITLE
Add params to specify which data values are presented on the delete dialog

### PR DESCRIPTION
**Pull request by cocinerox**

### CODE REVIEW

**Comment by DavidPatShuiFong** [comment]
Thank you László, this looks like a worthwhile change.

I suppose the underlying issue is that the delete dialog does not 'label' the columns in the same way that the add/update dialogs do?

**Comment by cocinerox** [comment]
Hi David! Yes, you're right. I assume the column labels are more informative for the user. Moreover, one may not want to show every column, just the important ones (or maybe no columns at all).

**Comment by DavidPatShuiFong** [comment]
Test example, works okay!

```{r}
library(shiny)
library(DTedit)

server <- function(input, output) {

  Grocery_List_Results <- dtedit(
    input, output,
    name = 'Grocery_List',
    thedata = data.frame(
      Buy = c('Tea', 'Biscuits', 'Apples'),
      Quantity = c(7, 2, 5),
      Comment = c('Irish', 'Not too sweet', 'Jonathan'),
      stringsAsFactors = FALSE
    ),
    edit.cols = c('Quantity', 'Comment'),
    view.cols = c('Buy', 'Comment'),
    show.delete = FALSE,
    show.insert = FALSE,
    show.copy = FALSE
  )
}

ui <- fluidPage(
  h3('Grocery List'),
  uiOutput('Grocery_List')
)

shinyApp(ui = ui, server = server)
```

**Comment by DavidPatShuiFong** [comment]
Test example, works okay!

```{r}
library(shiny)
library(DTedit)

server <- function(input, output) {
    
    Grocery_List_Results <- dtedit(
        input, output,
        name = 'Grocery_List',
        thedata = data.frame(
            Buy = c('Tea', 'Biscuits', 'Apples'),
            Quantity = c(7, 2, 5),
            Comment = c('Irish', 'Not too sweet', 'Jonathan'),
            stringsAsFactors = FALSE
        )
    )
}

ui <- fluidPage(
    h3('Grocery List'),
    uiOutput('Grocery_List')
)

shinyApp(ui = ui, server = server)
```

**Comment by DavidPatShuiFong** [comment]
Thanks @cocinerox !

**Comment by DavidPatShuiFong** [comment]
Added testing (testthat/shinytest) in 59215c299763e76ffbe740796ce094396eb3dd5e

`simple_modular` tests whether `delete.info.cols` and `delete.info.label.cols` results in failure to execute. Does not actually test effectiveness!

`error_test` checks for errors to be thrown (correctly) when there are basic errors in `delete.info.cols` and `delete.info.label.cols` arguments (thanks for writing the argument-checking code, @cocinerox!)

**Pull request merged**
