### PR TITLE
support for checkboxes / logical input

### LINKED ISSUE #19: support for radioButtons and checkboxInput
Could they (and possibly the other existing input controls) be added please, it would make the input forms much more rich than what they are now.

### PR DESCRIPTION
**Pull request by MatthiasHinz**
Hi, sorry for the delay. If you could leave the request open for a little while (~ until January 5th, the latest), I will add a test case for this.

Season's Greetings!

### CODE REVIEW

**Comment by DavidPatShuiFong** [comment]
Thanks @MatthiasHinz , looking forward to the test case! (I'm sure you know a lot more about software quality assurance than me...)

wishing you a Merry Christmas!

**Review by DavidPatShuiFong — COMMENTED** [review]
all changes look good

**Comment by MatthiasHinz** [comment]
@DavidPatShuiFong That's a relieve. I think the travis build is broken though because of system dependencies not configured.
Unfortunatily, I am still working on the test, but I will update asap.

**Comment by DavidPatShuiFong** [comment]
Yes, Travis builds now require adding `libgit2-dev` to the `.travis.yml`

I've added the following to `.travis.yml` in the `develop` branch

```
addons:
  apt:
    packages:
      - libgit2-dev

# libgit2-dev has become required
# for the gert dependency
# see https://github.com/r-lib/usethis/issues/1317
```

(the error in the Travis build without libgit2-dev)

```
----------------------------- ANTICONF -------------------------------

Configuration failed to find libgit2 library. Try installing:

 * brew: libgit2 (MacOS)

 * deb: libgit2-dev (Debian, Ubuntu, etc)

 * rpm: libgit2-devel (Fedora, CentOS, RHEL)

If libgit2 is already installed, check that 'pkg-config' is in your

PATH and PKG_CONFIG_PATH contains a libgit2.pc file. If pkg-config

is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:

R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'

-------------------------- [ERROR MESSAGE] ---------------------------

<stdin>:1:18: fatal error: git2.h: No such file or directory

compilation terminated.

----------------------------------------------------------------------

ERROR: configuration failed for package ‘gert’

* removing ‘/home/travis/R/Library/gert’

Error in i.p(...) : 

  (converted from warning) installation of package ‘gert’ had non-zero exit status

Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p

Execution halted
```

**Comment by DavidPatShuiFong** [comment]
@MatthiasHinz , I'm going to accept this pull request now! Mainly because my own example code is now going to depend on the bugfix provided in this, thank you!

I know you would like to add testing, for which I would love to see/review/accept another pull request!

**Pull request merged**
